create table if not exists public.connection_test (
  id bigint generated by default as identity primary key,
  message text not null unique,
  created_at timestamp with time zone default now() not null
);

insert into public.connection_test (message)
values
  ('Supabase connection is working'),
  ('ERP dashboard seed row'),
  ('Inventory sync sample row'),
  ('Customer record sample row'),
  ('Orders table test row')
on conflict do nothing;
